/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class WaBot {
  constructor(dbPath: string, callback: ((err: Error | null, arg: string) => any))
  /**
   * # Safety
   * This function is unsafe because it spawns a task that runs the bot.
   */
  start(): Promise<void>
  sendMessage(toJid: string, text: string): Promise<string>
}
