/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class WaBot {
  constructor(dbPath: string, eventCallback: ((err: Error | null, arg: string) => any))
  start(): Promise<void>
  sendMessage(toJid: string, text: string): Promise<string>
}
