/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class WaBot {
  constructor(dbPath: string, eventCallback: ((err: Error | null, arg: string) => any), sendFrameCallback: ((err: Error | null, arg: Buffer) => any))
  /**
   * # Safety
   * This function is unsafe because it spawns a task that runs the bot.
   */
  start(): Promise<void>
  sendMessage(toJid: string, text: string): Promise<string>
  notifyConnected(): Promise<void>
  receiveFrame(frame: Buffer): Promise<void>
  notifyDisconnected(): Promise<void>
}
